acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

login:
    pattern:   /login
    defaults:  { _controller: AcmeTaskBundle:Security:login }

login_check:
    pattern:   /login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"