security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_CREATE
        ROLE_CREATE: ROLE_VIEW

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    alex:
                        password: mypass
                        roles: 'ROLE_VIEW'
                    admin:
                        password: adminpass
                        roles: 'ROLE_SUPER_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: chain_provider
                #csrf_provider: security.csrf.token_manager
                #login_path: /login
                #check_path: /login_check
                always_use_default_target_path: true
                default_target_path: home_page
            logout:
                path: /logout
                target: /task/

    access_control:
        - { path: ^/task/show, roles: ROLE_VIEW }
        - { path: ^/task/new, roles: ROLE_CREATE }
        - { path: ^/task/task_update, roles: ROLE_EDIT}

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
