services:
    acme_task_bundle:
        class: Acme\TaskBundle\Form\Type\TaskType
        tags:
            - { name: form.type, alias: task}
    security.access.task.voter:
        class: Acme\TaskBundle\Security\Authorization\Voter\TaskVoter
        calls:
            - [setTokenStorage,['@security.token_storage']]
        public: false
        tags:
            - { name: security.voter }
    my.listener:
        class: Acme\TaskBundle\EventListener\SetRole
        calls:
            - [setTokenStorage,['@security.token_storage']]
        tags:
            - { name: doctrine.event_listener, event: prePersist }